version: '3.8'
services:

  db:
    image: postgres
    restart: always
  
    env_file:
      - ./.env
    ports:
      - 5435:5432

    volumes:
      - ./data:/var/lib/postgresql/data

  # backend:
  #   build: ./backend
  #   network_mode: host
  #   depends_on:
  #   - db

  # frontend:
  #   build: ./frontend
  #   ports:
  #   - 3001:3000

  #   depends_on:
  #   - backend





  

