version: '3.8'
services:

  db:
    image: postgres
    restart: always
  
    env_file:
      - ./.env
    ports:
      - 5435:5432

    volumes:
      - ./data:/var/lib/postgresql/data

  backend:
    build: ./backend
    
    ports:
      - 8002:8000
      - 6002:6001

    volumes:
      - /etc/letsencrypt/live/bluff.website/fullchain.pem:/app/ssl/fullchain.pem
      - /etc/letsencrypt/live/bluff.website/privkey.pem:/app/ssl/privkey.pem
    
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
    - 3002:3000
    
    depends_on:
    - backend

